import './globals.css'
import type { Metadata } from 'next'
import { Nunito_Sans,Work_Sans } from 'next/font/google'



 
const nunito_sans = Nunito_Sans({
  weight: ['300','400','700','800'],
  subsets: ['latin'],
  variable: '--font-nunito',
 
})

const work_Sans = Work_Sans({
  weight: ['300','400','700','800'],
  subsets: ['latin'],
  variable: '--font-work',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={`${nunito_sans.variable}  font-sans`}>{children}</body>
    </html>
  )
}
